import { test, expect } from '../fixtures';

/**
 * Generated by the stage 06 pipeline from tickets/WSP-101.md (criterion 1),
 * then reviewed to house style (fixtures import instead of @playwright/test).
 */
test.describe('Login error handling', () => {
  test('locked-out user sees the lockout error and stays on /login', async ({
    page,
  }) => {
    await page.goto('/login');
    await page.getByTestId('username').fill('locked_out_user');
    await page.getByTestId('password').fill('workshop123');
    await page.getByTestId('login-submit').click();

    await expect(page.getByTestId('login-error')).toHaveText(
      'Sorry, this user has been locked out.'
    );
    await expect(page).toHaveURL(/\/login$/);
  });
});
