import { test, expect } from '../fixtures';

/**
 * Generated by the stage 06 pipeline from tickets/WSP-101.md (criterion 3),
 * then reviewed to house style.
 */
test.describe('Login error handling', () => {
  test('correcting credentials after a failed attempt signs in', async ({
    page,
  }) => {
    await page.goto('/login');

    // First attempt: wrong password
    await page.getByTestId('username').fill('standard_user');
    await page.getByTestId('password').fill('wrong-password');
    await page.getByTestId('login-submit').click();
    await expect(page.getByTestId('login-error')).toBeVisible();

    // Second attempt: correct credentials
    await page.getByTestId('password').fill('workshop123');
    await page.getByTestId('login-submit').click();

    await expect(page).toHaveURL(/\/inventory$/);
    await expect(page.getByRole('heading', { name: 'Products' })).toBeVisible();
  });
});
