import { test, expect } from '../fixtures';

/**
 * Generated by the stage 06 pipeline from tickets/WSP-101.md (criterion 2),
 * then reviewed to house style.
 */
test.describe('Login error handling', () => {
  test('wrong password shows the mismatch error and stays on /login', async ({
    page,
  }) => {
    await page.goto('/login');
    await page.getByTestId('username').fill('standard_user');
    await page.getByTestId('password').fill('wrong-password');
    await page.getByTestId('login-submit').click();

    await expect(page.getByTestId('login-error')).toHaveText(
      'Username and password do not match any user in this service'
    );
    await expect(page).toHaveURL(/\/login$/);
  });
});
